// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PhotoMetadata;
using System;

namespace PhotoMetadata.Migrations
{
    [DbContext(typeof(PhotoContext))]
    partial class PhotoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhotoMetadata.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateTaken");

                    b.Property<string>("EquipManufacturer");

                    b.Property<string>("EquipModel");

                    b.Property<double?>("FNumber");

                    b.Property<double?>("FocalLength");

                    b.Property<string>("FullPath");

                    b.Property<int>("Height");

                    b.Property<int?>("ISO");

                    b.Property<string>("Name");

                    b.Property<double?>("ShutterSpeed");

                    b.Property<string>("SoftwareUsed");

                    b.Property<int>("Width");

                    b.HasKey("PhotoId");

                    b.ToTable("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
